name: Check licenses

on:
  pull_request:
    types: [locked]
  pull_request_review_comment:
    types: [deleted, created, edited]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.74.0
          override: true
      - name: Verify Licenses
        run: |
          echo "This a custom execution !"
